# Generated by Django 4.1.7 on 2023-03-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
